### ISSUE TITLE
Missing dictionnary

### ISSUE THREAD

**Issue by grems6** [willemdh/logstash_filter_f5#2]
Hi,

Thanks for the configuration files. It will save me a lot of time :)

However, when I tried to apply your configuration, I couldn't find the file outputs.yml. Did you forgot to commit it ?

In advance thank you,

Regards,

grems6

**Comment by willemdh** [comment]
Nope the outputs.yml is jsut a way to dynamically allocate the name of the index where to store the data. The content of my outputs.yml is just a bunch of types with the name of the index where to store them. As this seems to be very confusing I'm going to omit it from the grok expression.. 
I'm working with some other F5 sysadmins to streamline them a bit more so the work out of the box for everyone. Did the expressions work out of the box for you or did you have to make some changes?

**Comment by grems6** [comment]
Thanks for the quick answer. I can see my log in Kibana but I got some grokparsefailure. I need to check more precisely which grok and why it fails.

**Comment by willemdh** [comment]
Make sure you try the latest commit, I changed several things which could help.
